=== TerletskiySergey/EP_AUTUMN_2015_TASK3/variant8/resources/warplanes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
        targetNamespace="http://warplanes.org/target" xmlns:trg="http://warplanes.org/target">
    <!--xmlns:trg1="http://countries.org/target"-->
    <include schemaLocation="countries.xsd"/>
    <!--<import schemaLocation="countries.xsd" namespace="http://countries.org/target"/>-->
    <element name="planes">
        <complexType>
            <sequence>
                <element name="plane" type="trg:planeType" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <simpleType name="unitType">
        <restriction base="string">
            <enumeration value="yard"/>
            <enumeration value="foot"/>
            <enumeration value="meter"/>
        </restriction>
    </simpleType>
    <complexType name="planeType">
        <sequence>
            <element name="model" type="trg:modelType"/>
            <element name="origin" type="trg:countriesType"/>
            <element name="tech-chars" type="trg:charsType"/>
            <element name="price" type="trg:priceType" minOccurs="0"/>
        </sequence>
    </complexType>
    <complexType name="charsType">
        <sequence>
            <element name="type">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="CHASE_PLANE"/>
                        <enumeration value="FIGHTER"/>
                        <enumeration value="INTERCEPTOR"/>
                        <enumeration value="SPY_PLANE"/>
                        <enumeration value="SUPPORT_AIRCRAFT"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="crew">
                <simpleType>
                    <restriction base="positiveInteger">
                        <minInclusive value="1"/>
                        <maxInclusive value="2"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="armament" minOccurs="0">
                <complexType>
                    <sequence>
                        <element name="missile">
                            <simpleType>
                                <restriction base="unsignedInt">
                                    <minInclusive value="0"/>
                                    <maxInclusive value="10"/>
                                </restriction>
                            </simpleType>
                        </element>
                    </sequence>
                </complexType>
            </element>
            <element name="radar">
                <complexType>
                    <attribute name="avail" type="boolean"/>
                </complexType>
            </element>
            <element name="geom-pars">
                <complexType>
                    <sequence>
                        <element name="length">
                            <complexType>
                                <simpleContent>
                                    <extension base="trg:unsignedDouble">
                                        <attribute name="units" use="required" type="trg:unitType"/>
                                    </extension>
                                </simpleContent>
                            </complexType>
                        </element>
                        <element name="span">
                            <complexType>
                                <simpleContent>
                                    <extension base="trg:spanType">
                                        <attribute name="units" use="required" type="trg:unitType"/>
                                    </extension>
                                </simpleContent>
                            </complexType>
                        </element>
                        <element name="height">
                            <complexType>
                                <simpleContent>
                                    <extension base="trg:unsignedDouble">
                                        <attribute name="units" use="required"/>
                                    </extension>
                                </simpleContent>
                            </complexType>
                        </element>
                    </sequence>
                </complexType>
            </element>
        </sequence>
    </complexType>
    <complexType name="priceType">
        <simpleContent>
            <extension base="trg:unsignedDouble">
                <attribute name="order" use="required">
                    <simpleType>
                        <restriction base="string">
                            <enumeration value="million"/>
                            <enumeration value="thousand"/>
                            <enumeration value="hundred"/>
                        </restriction>
                    </simpleType>
                </attribute>
                <attribute name="currency" fixed="thaler" use="required"/>
            </extension>
        </simpleContent>
    </complexType>

    <simpleType name="modelType">
        <restriction base="ID">
            <minLength value="3"/>
        </restriction>
    </simpleType>
    <simpleType name="unsignedDouble">
        <restriction base="double">
            <minInclusive value="0"/>
        </restriction>
    </simpleType>
    <simpleType name="spanList">
        <list itemType="trg:unsignedDouble"/>
    </simpleType>
    <simpleType name="spanType">
        <restriction base="trg:spanList">
            <minLength value="1"/>
            <maxLength value="2"/>
        </restriction>
    </simpleType>
    <simpleType name="countriesListTwoLetterAcronyms">
        <list itemType="trg:countryTypeTwoLettersAcronyms"/>
    </simpleType>
    <simpleType name="countriesListThreeLetterAcronyms">
        <list itemType="trg:countryTypeThreeLettersAcronyms"/>
    </simpleType>
    <simpleType name="countriesListEngNotation">
        <list itemType="trg:countryTypeEngNotation"/>
    </simpleType>
    <simpleType name="countriesType">
        <union memberTypes="trg:countriesListTwoLetterAcronyms
        trg:countriesListThreeLetterAcronyms
        trg:countriesListEngNotation"/>
    </simpleType>
</schema>

=== TerletskiySergey/EP_AUTUMN_2015_TASK3/variant8/resources/warplanes.xml
<?xml version="1.0" encoding="UTF-8"?>
<planes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://warplanes.org/target warplanes.xsd"
        xmlns="http://warplanes.org/target">
    <plane>
        <model>Grumman_OV-1_Mohawk</model>
        <origin>USA</origin>
        <tech-chars>
            <type>SPY_PLANE</type>
            <crew>2</crew>
            <radar avail="true"/>
            <geom-pars>
                <length units="meter">12.5</length>
                <span units="meter">14.63</span>
                <height units="meter">3.86</height>
            </geom-pars>
        </tech-chars>
    </plane>
    <plane>
        <model>Миг-29</model>
        <origin>Russia</origin>
        <tech-chars>
            <type>FIGHTER</type>
            <crew>2</crew>
            <armament>
                <missile>4</missile>
            </armament>
            <radar avail="true"/>
            <geom-pars>
                <length units="meter">17.32</length>
                <span units="meter">11.36</span>
                <height units="meter">4.73</height>
            </geom-pars>
        </tech-chars>
        <price order="million" currency="thaler">30</price>
    </plane>
    <plane>
        <model>Vought_F-8_Crusader</model>
        <origin>USA</origin>
        <tech-chars>
            <type>FIGHTER</type>
            <crew>1</crew>
            <armament>
                <missile>4</missile>
            </armament>
            <radar avail="true"/>
            <geom-pars>
                <length units="meter">16.53</length>
                <span units="meter">6.86 10.87</span>
                <height units="meter">4.8</height>
            </geom-pars>
        </tech-chars>
    </plane>
    <plane>
        <model>F-14D_Super_Tomcat</model>
        <origin>USA</origin>
        <tech-chars>
            <type>INTERCEPTOR</type>
            <crew>2</crew>
            <armament>
                <missile>8</missile>
            </armament>
            <radar avail="true"/>
            <geom-pars>
                <length units="meter">19.1</length>
                <span units="meter">11.65 19.45</span>
                <height units="meter">4.88</height>
            </geom-pars>
        </tech-chars>
        <price order="million" currency="thaler">38</price>
    </plane>
</planes>
